### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by equinusocio** [ihodev/sublime-da-ui#13]
Now I see why you told me that you didn't have time for a new premium theme ;)
You just stolen my idea :)

**Comment by ihodev** [comment]
@equinusocio I'm sorry you feel that way :worried: 

As I recall we discussed the idea to jointly develop a new theme at the end of November, 2016. But I was really busy at work starting December, 2016 and had no time for that.

At the beginning of March, 2017 I finished the most important tasks at work and got some free time. I've decided to start development alone, because I didn't know how much time it takes and could not promise that I'll be able to finish "X" feature till "DATE". Teamwork requires effective collaboration, responsibilities and good planning. Unfortunately, I couldn't provide that from my side, because I work on the pet projects in my spare time.

I hope you understand.

BTW, the idea wasn't new, see [Monokai Pro](https://www.monokai.pro/) :wink:
