### ISSUE TITLE
Inquiry on Share The Love -> Pricing

### ISSUE THREAD

**Issue by storrgie** [ihodev/sublime-da-ui#2]
I've recently followed you on patreon because I appreciate your work. I was excited to see an announcement come through for this project, however I am wondering about why you're planning to move to a payment model rather than patreon.

**Comment by ihodev** [comment]
Hi, @storrgie! I have good news, you'll get it for free once we reach to stable version 1.0.0. I just have left this information for the future post at Patreon, however the announcement at ST Forum will include next message:

> I appreciate your support. I've decided that everyone who supported my projects (A File Icon, Boxy Theme) at Patreon before this announcement will get it for free once we reach to stable version 1.0.0.

P.S.
> I am wondering about why you're planning to move to a payment model rather than patreon.

I'll write some explanation later this week why I've decided so.

P.P.S.
I hope you'll like it :wink:

**Comment by storrgie** [comment]
Thanks for the response.

Every person is different, and I am incredibly appreciative of the type of work you do where you're making someone's primary tools beautiful. I just wanted to share why I became a patron, as I think others might resonate. 

For me, I felt an obligation to support you once I realize you had made that mechanism available via the "Share The Love" sections of your readme(s). Not everyone feels that way. But, hand in hand with that. I'm wary to use your new DA UI because your intent is no longer to release it as gratis. I'm still happy to be a patron, I look at the boxy theme daily. I'd hope others would support you so that you'd not have to consider paywall'ing your work.

Ultimately you should seek out the most reasonable method to support continued creation of your art.

**Comment by ihodev** [comment]
### Why I've Decided to Move to a Payment Model for DA UI

Creating a basic theme isn't hard. You won't see the rocket science in the code of an one-purpose theme. That was not a problem, I could create another one. However, UI is subjective. What some users love, others hate. So it's logical to offer the mechanism of customization and it should be as flexible as it able to be. That's the hard part. It requires a lot of time for developing, tweaking, testing, etc. Also you need to provide good defaults to minimize the customization part.

I've put a lot of time and effort into making DA UI. I've rewritten it twice because of the new theme engine to support the latest and the gratest Sublime Text features. And there is a lot of work to be done, cause the aim is to provide the UI that fits your needs.

Unfortunately, themes for other tools are one of those niche projects. So, crowdfunding may not be really effective. That is understandable, personally I can support only a few products. I am at Patreon for about 1.5 year and I've earned for only a week of my daily work, however I've spend months into making my projects and I continue to work on them. 

> My family doesn't like open source projects, because I spend my free time on them :smile: 

*That's why I hope a payment model will be able to cover the costs of development at least.*

I'm just trying to make myself useful and do my best. Personally I don't need dozens of features that some of my projects bring. However I think that they have to be available.

**A big thank you for the kind words and your support! I hope you'll understand.**

P.S. In any case you'll never see [something like this](http://www.techrepublic.com/article/how-startup-kite-tried-to-ruin-two-open-source-communities/) in my projects.
P.P.S. Sorry for my English. I'm still learning it 😜

**Comment by nklmilojevic** [comment]
Just please go with the one payment and not with the subscription model. 

P.S. Thanks for the great theme.
